
USE heroku_f62f801bb094f11;
DROP TABLE IF EXISTS SETTING;
CREATE TABLE SETTING (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(60),
english VARCHAR(90),
PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS VAL;
CREATE TABLE VAL(
id INT NOT NULL AUTO_INCREMENT,
tf BOOLEAN, 
val INT(11), 
string VARCHAR(30),
PRIMARY KEY (ID)
);