DROP DATABASE IF EXISTS inidb;
CREATE DATABASE inidb;
USE inidb;
CREATE TABLE SETTING (
id INT NOT NULL AUTO_INCREMENT,
name VARCHAR(60),
PRIMARY KEY (ID)
);
CREATE TABLE VAL(
id INT NOT NULL AUTO_INCREMENT,
tf BOOLEAN, 
val INT(11), 
string VARCHAR(30),
PRIMARY KEY (ID)
);